version: "3.8"

services:
  api:
    build:
      context: ./api
    container_name: ner_api
    ports:
      - "8001:8001"
    environment:
      - PYTHONUNBUFFERED=1

  adk:
    build:
      context: ./adk
    container_name: adk_agent
    ports:
      - "8000:8000"
    environment:
      - API_URL=http://api:8001
    depends_on:
      - api
