[project]
name = "adk"
version = "1.0.0"
description = "Agent using Google ADK"
authors = [
    {name = "Gustavo Ragazzi Amorim",email = "ragazzi@hotmail.com.br"}
]
package-mode = false
readme = "../README.md"
requires-python = ">=3.13"
dependencies = ["google-adk (>=1.2.1,<2.0.0)"]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
